spring:
  data:
    mongodb:
#      uri: mongodb+srv://ujmlee0524:mDmWSelEHWZUGMPH@test.xjtpazh.mongodb.net/test
      uri: mongodb://localhost:27017/test
      auto-index-creation: true
logging:
  level:
    org:
      springframework:
        org.springframework.web: trace
        org.springframework.web.multipart: trace
        data:
          mongodb: DEBUG
server:
  tomcat:
    connection-timeout: 3000
    max-threads: 200